[project]
name = "pomodora-clock"
version = "0.1.0"
description = "A simple pomodora clock"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "pygame>=2.6.1",
    "ttkbootstrap>=1.13.11",
]
